image: atnartur/docker:latest


stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - export
    - docker-compose -f docker-compose.prod.yml up -d --remove-orphans --build
  tags:
    - simplecrm-prod
  only:
    - master
