version: '3'

services:
  nginx:
    image: simplecrm-nginx:latest
    ports:
      - 80:80
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    depends_on:
      - app
    restart: always

  app:
    image: simplecrm-app:latest
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
    restart: always

  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: simplecrm
      POSTGRES_USER: simplcrm
      POSTGRES_PASSWORD: simplcrm
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
